#!/bin/sh
set -e

version="$1"
image_path="$2"

[ -n "$version" ] || exit 1
[ -n "$image_path" ] || exit 1

echo "Building UKI for kernel $version." >&2

# make sure the target directory exists:
install -d /boot/efi/EFI/ubuntu

ukify build --linux /boot/vmlinuz-$version --initrd /boot/initrd.img-$version --output /boot/efi/EFI/ubuntu/$version.efi --uname $version || {
    echo "UKI build FAILED for kernel version $version." >&2
    exit 1
}
